# Linear algebra

The best way to work with vectors and matrices in Python is to use the `numpy` library. This library is frequently used in machine learning and data science. 

First, we need to import the library

In [43]:
import numpy as np

### Vectors

A 1d array can be used to represent a vector

In [44]:
a = np.array([1,2,3,4])

print("Dimension: ", a.ndim) # number of dimensions of the array
print("Shape: ", a.shape) # Tuple of ndim numbers. In this case, row count.
print("Size: ", a.size) # Total number of entries

Dimension:  1
Shape:  (4,)
Size:  4


One way to convert a row vector (standard array) into a column vector (2d array with 1 column) is to use re-shape.

In [45]:
col = a.reshape(4, 1)
col

array([[1],
       [2],
       [3],
       [4]])

### Matrices

A 2d array can be used to represent matrices

In [47]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
print("Dimension: ", A.ndim) # number of dimensions of the array
print("Shape: ", A.shape) # Tuple of ndim numbers. In this case, rows and columns.
print("Size: ", A.size) # Total number of entries

Dimension:  2
Shape:  (2, 3)
Size:  6


The np matrix object created with `.asmatrix` is a 2d array with some additional arithmetic support for matrix operations.

In [48]:
M = np.asmatrix(A)
M

matrix([[1, 2, 3],
        [4, 5, 6]])

In [49]:
M.T # Transpose

matrix([[1, 4],
        [2, 5],
        [3, 6]])

For matrices of complex numbers, the `.H` attribute returns the conjugate transpose.

In [51]:
c_array = np.array([1, 1+2j, 1-3j, 1])
c_mat = np.asmatrix(c_array.reshape(2,2))
print("Matrix:")
print(c_mat)
print("Conjugate transpose: ")
print(c_mat.H)

Matrix:
[[1.+0.j 1.+2.j]
 [1.-3.j 1.+0.j]]
Conjugate transpose: 
[[1.-0.j 1.+3.j]
 [1.-2.j 1.-0.j]]


The `.I` attribute returns the inverse of the matrix.

In [50]:
c_mat.I

matrix([[-0.16216216-0.02702703j,  0.10810811+0.35135135j],
        [ 0.24324324-0.45945946j, -0.16216216-0.02702703j]])

### Indexing

We can access elements of an array with indices analogously to the way Python accesses list elements. 

In [55]:
a[0] # recall a = [1,2,3,4] above


np.int64(1)

We can also use index to extract an array slice, analagously to the way lists work in Python.

In [56]:
a[1:3]

array([2, 3])

In the case of 2d arrays (or more), we can access elements by separating indices of the internal arrays by commas. 

In [59]:
A = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(A)
print(A[2, 1]) # prints the item at row index 2, col index 1

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
8


Slicing can also be done on multiple dimensional arrays. In this case, we find a sub-matrix by taking a slice of rows, then a slice of columns, separated by commas.

In [60]:
S = A[1:3, 1:3]
print(S)

[[5 6]
 [8 9]]


### Special matrices

In [ ]:
# N by N Identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
# Zeros matrix
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
# Ones matrix
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
# An example. Checkerboard pattern of 1s and 0s
M = np.zeros([4,4])
M[:2, 2:] = np.ones([2,2])
M[2:, :2] = np.ones([2,2])
M

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.]])

### Vector operations

#### Dot product

In [75]:
v = np.array([1,2,3])
w = np.array([5,4,2])

np.dot(v, w)

np.int64(19)

#### Vector length (norm, magnitude)

Vector length is the square root of the sum of the squares of the lengths on each dimension (a generalization of the Pythagorean theorem). The length of an $n$ dimensional vector $\vec{v} = [v_1, v_2, \ldots, v_n]$ is

$$
\begin{aligned}
|\vec{v}|&=\sqrt{v_{1}^{2}+v_{2}^{2}+\cdots + v_{n}^{2}}\\
&= \sqrt{\vec{v}\cdot \vec{v}}
\end{aligned}
$$

In [76]:
v = np.array([3,4])
np.sqrt(np.dot(v,v))

np.float64(5.0)

#### Angle between two vectors

The angle $\theta$ between two angles satisfies 

$$
\cos{\theta} = \frac{\vec{a}\cdot \vec{b}}{|a||b|}
$$

In [77]:
a = np.array([1,0])
b = np.array([1,1])

np.arccos( (np.dot(a,b)) / (np.sqrt(np.dot(a,a)*np.dot(b,b)) ) )

np.float64(0.7853981633974484)

Which is the decimal value of $\frac{\pi}{4}$

In [78]:
np.pi/4

0.7853981633974483

### Matrix operations

Matrix addition is carried out with `+`

In [80]:
A = np.array([1,1,1,1]).reshape(2,2)
B = np.array([3,4,5,6]).reshape(2,2)
A+B


array([[4, 5],
       [6, 7]])

Matrix multiplication is carried out with `@`

In [83]:
A = np.array([1,1,1,1]).reshape(2,2)
B = np.array([3,4,5,6]).reshape(2,2)
print(A)
print(B)
A@B

[[1 1]
 [1 1]]
[[3 4]
 [5 6]]


array([[ 8, 10],
       [ 8, 10]])

Or using `numpy.matmul`

In [84]:
np.matmul(A,B)

array([[ 8, 10],
       [ 8, 10]])

Note that the `*` symbol does elementwise multiplication, not matrix multiplication 

In [85]:
A = np.array([2,0,0,3]).reshape(2,2)
B = np.array([5,5,5,5]).reshape(2,2)
A*B

array([[10,  0],
       [ 0, 15]])